### ISSUE TITLE
YoLink devices from YoSmart

### ISSUE THREAD

**Issue by evectis** [helium/devdocs#108]
Hello, have any of the YoLink devices listed here been tested and vetted?
http://www.yosmart.com/products-list 
They are "LoRa enabled".

**Comment by kent-williams** [comment]
Hello @evectis,

Unfortunately it looks like YoLink uses a proprietary LoRa protocol.  [LoRa](https://www.semtech.com/lora) is an LPWAN technology developed by Semtech, and LoRaWAN is a networking layer built on top of LoRa. The Helium Network uses LoRaWAN, and therefore requires that devices be LoRaWAN compatible, you can read more about our network design [here](https://developer.helium.com/longfi/introduction).

> “YoLink” is a proprietary wireless technology provided by YoSmart. which is based on the Semtech’s LoRa wireless technology combined the YoSmart smart home/buiding protocol, to provide most advanced smart home/buidling devices solution.
