### ISSUE TITLE
Duplicate Hotspot table section in JSON Schema documentation

### ISSUE THREAD

**Issue by marcblum** [helium/devdocs#113]
Hi,

The following file has a duplicate of the Hotspot table where the Metadata should be documented.

[devdocs/console/integrations/json-schema.md](https://github.com/helium/devdocs/blob/master/console/integrations/json-schema.md)

I would submit a pull request if I knew exactly what the documentation should entail :)

Regards,
Marc

**Comment by kent-williams** [comment]
Thank you @marcblum
