### ISSUE TITLE
Add explanation of what happens when multiple hotspots receive and route the same packet from a sensor

### ISSUE THREAD

**Issue by AndyFooBlah** [helium/devdocs#118]
Propose that the writeup in https://developer.helium.com/blockchain/mining-token-rewards include an explanation of what happens when a packet from a sensor is received by multiple hotspots.  Specifically, which hotspot(s) are rewarded for the routing and how that determination is made.

**Comment by PharkMillups** [comment]
Thanks. I'll take a pass at this next week.
