### ISSUE TITLE
A documentation suggestion for the Server

### ISSUE THREAD

**Issue by MoonlightsBlueShadow** [helium/devdocs#132]
You have a RED BOX around the items that need changing.  Nice / Clean / Easy visual, you set me up for failure.  
  In the Server area, your documentation shows the Server Address is 192,168.2.12
  Your text says the address should be the IP Address of your Helium Network Server.

Please delete the IP address of “192,168.2.12” replace it XXX.XXX.XXX.XXX and a NOTE that says
“YOUR HELIUM NETWORK SERVER IP ADDRESS”

I think it may help people who don't follow the instructions.

**Comment by kent-williams** [comment]
Hello @MoonlightsBlueShadow can you please indicate what doc you are referring to.

**Comment by PharkMillups** [comment]
This one here. 

https://developer.helium.com/hotspot/lorawan-gateway-migration/multitech-conduit
