### ISSUE TITLE
Mistake in images on developer-setup.md

### ISSUE THREAD

**Issue by davetapley** [helium/devdocs#134]
I think this image is wrong:

> When you buy a Helium Hotspot, you are buying a Packet Forwarder and a Miner in a convenient package:
![](https://github.com/helium/devdocs/blob/master/.gitbook/assets/artboard-copy-67.png?raw=true)

https://github.com/helium/devdocs/blob/master/hotspot/developer-setup.md

---

I _presume_ the rightmost box should say 'Helium Miner', like this:
![](https://raw.githubusercontent.com/helium/devdocs/master/.gitbook/assets/artboard%20(1).png)

--- 

I'd make a PR but it from the filename I'm guessing these came from Illustrator.

**Comment by davetapley** [comment]
The image below it also appears to be wrong for the same reason:
![](https://github.com/helium/devdocs/blob/master/.gitbook/assets/artboard-copy-68.png)

**Comment by lthiery** [comment]
@davetapley thanks for raising this! working on the fix
